apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-multitool
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mikarnik/training-model.git
    targetRevision: HEAD
    path: nginx-multitool
  destination:
    namespace: nginx-multitool
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true