apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
  labels:
    cluster: c1
    app: minio
spec:
  project: default
  source:
    repoURL: https://github.com/mikarnik/training-model.git
    targetRevision: HEAD
    path: minio
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true