# Build binaries
FROM golang:1.14 as builder

WORKDIR /src/
COPY . .

RUN mkdir -p /build_out && \
	CGO_ENABLED=0 go build -o /build_out/kad

# Copy binaries to image
FROM debian
LABEL maintainer="tomkukral"

RUN apt-get update && \
  apt-get install -y curl procps && \
  rm -rf /var/lib/apt/lists/*

COPY --from=builder /build_out/kad /bin/

CMD ["/bin/kad"]
